<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Model - Kopieren %283%29\**" />
    <Compile Remove="Model - Kopieren %284%29\**" />
    <Compile Remove="Model - Kopieren %285%29\**" />
    <Compile Remove="Model\**" />
    <Compile Remove="obj - Kopieren\**" />
    <Compile Remove="ViewModel\**" />
    <Compile Remove="View\**" />
    <EmbeddedResource Remove="Model - Kopieren %283%29\**" />
    <EmbeddedResource Remove="Model - Kopieren %284%29\**" />
    <EmbeddedResource Remove="Model - Kopieren %285%29\**" />
    <EmbeddedResource Remove="Model\**" />
    <EmbeddedResource Remove="obj - Kopieren\**" />
    <EmbeddedResource Remove="ViewModel\**" />
    <EmbeddedResource Remove="View\**" />
    <None Remove="Model - Kopieren %283%29\**" />
    <None Remove="Model - Kopieren %284%29\**" />
    <None Remove="Model - Kopieren %285%29\**" />
    <None Remove="Model\**" />
    <None Remove="obj - Kopieren\**" />
    <None Remove="ViewModel\**" />
    <None Remove="View\**" />
    <Page Remove="Model - Kopieren %283%29\**" />
    <Page Remove="Model - Kopieren %284%29\**" />
    <Page Remove="Model - Kopieren %285%29\**" />
    <Page Remove="Model\**" />
    <Page Remove="obj - Kopieren\**" />
    <Page Remove="ViewModel\**" />
    <Page Remove="View\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\" />
    <Folder Include="ViewModels\" />
    <Folder Include="Views\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="MySql.Data" Version="9.6.0" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
  </ItemGroup>

</Project>
